name: cisTEM GPU release no experimental full build

on:
  push:
    branches: 
      - master
      - '*_with_ci'
  pull_request:
    branches: master

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_no_experimental_full"
      configure_options: "--with-cuda "
      global_configure_options: " --enable-openmp --disable-multiple-global-refinements --enable-smooth-mip --with-wx-config=/opt/WX/icc-static/bin/wx-config"
      runs_on_os: ubuntu-latest
      CC: icc
      CXX: icpc
      cppstandard: 17
      run_tests: false
      n_threads: 4
