name: cisTEM GPU release, GNU MKL

on:
  push:
    branches: 
      - master
      - '*_with_ci'
  pull_request:
    branches: master

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_GNU_MKL"
      configure_options: "--with-cuda "
      global_configure_options: " --enable-openmp --enable-experimental --with-wx-config=/opt/WX/gcc-static/bin/wx-config --disable-multiple-global-refinements --enable-smooth-mip "
      runs_on_os: ubuntu-latest
      CC: gcc
      CXX: g++
      cppstandard: 17
      run_tests: false
      n_threads: 4
